print(0)
n = 2
for i in range(n):
    print(i)
raise ValueError("An error occurred")